services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  vertica:
    image: vertica/vertica-ce:12.0.3-0
    container_name: vertica-server
    ports:
      - "5433:5433"  # Vertica port
    environment:
      DATABASE_NAME: VMart
      DATABASE_USER: dbadmin
    volumes:
      - vertica_data:/opt/vertica/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "/opt/vertica/bin/vsql", "-U", "dbadmin", "-d", "VMart", "-c", "SELECT 1;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  clickhouse_data:
  vertica_data:

networks:
  default:
    name: theatre_network_d