# version: '3'
services:
  service:
    build: django/
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - theatre-db
    volumes:
      - static-data:/var/www/static/
    networks:
      - theatre_network_d
      - auth-service_auth_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static-data:/var/www/static/
    depends_on:
      - service
    ports:
      - "80:80"
    networks:
      - theatre_network_d

  theatre-db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - theatre_network_d

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - theatre_network_d

  movies-etl:
    build: etl/
    env_file:
      - etl/.env
    volumes:
      - ./state:/app/state
    networks:
      - theatre_network_d

  theatre-redis:
    image: redis
    networks:
      - theatre_network_d 

  fastapi:
    build: fastapi/
    ports:
      - "9000:9000"
    env_file:
      - fastapi/.env
    depends_on:
      - elasticsearch
      - service
      - theatre-redis
    networks:
      - theatre_network_d
      - auth-service_auth_network

  ugc-service:
    build: ugc-service/
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=ugc_service
    depends_on:
      - mongodb
    networks:
      - theatre_network_d
      - auth-service_auth_network

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - theatre_network_d

volumes:
  static-data:
  esdata:
  postgres_data:
  mongodb_data:

networks:
  theatre_network_d:
    name: theatre_network_d
  auth-service_auth_network:
    external: true
