"""update_token_blacklist_table

Revision ID: 7e5ac01a2439
Revises: 52e144f251b2
Create Date: 2025-03-16 01:55:14.667937+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7e5ac01a2439"
down_revision: str | None = "52e144f251b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "token_blacklist",
    #     "jti",
    #     existing_type=sa.VARCHAR(length=36),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    op.drop_index("ix_token_blacklist_token", table_name="token_blacklist")
    op.drop_index("ix_token_blacklist_token_jti", table_name="token_blacklist")
    # Use execute to run raw SQL with the USING clause
    op.execute('ALTER TABLE token_blacklist ALTER COLUMN jti TYPE UUID USING jti::uuid')
    op.create_index(
        "ix_token_blacklist_token_jti", "token_blacklist", ["jti"], unique=False
    )
    op.drop_column("token_blacklist", "token")
    op.add_column(
        "users", sa.Column("token_version", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    op.add_column(
        "token_blacklist",
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_token_blacklist_token_jti", table_name="token_blacklist")
    op.create_index(
        "ix_token_blacklist_token_jti",
        "token_blacklist",
        ["token", "jti"],
        unique=False,
    )
    op.create_index(
        "ix_token_blacklist_token", "token_blacklist", ["token"], unique=False
    )
    op.alter_column(
        "token_blacklist",
        "jti",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
