"""add_anonymous_users

Revision ID: a29b065685e5
Revises: 7e5ac01a2439
Create Date: 2025-03-21 00:42:04.373875+00:00

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "a29b065685e5"
down_revision: str | None = "7e5ac01a2439"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
