"""add_audit_log_table

Revision ID: a9c7a10d6970
Revises: f991fb728e0a
Create Date: 2025-03-13 02:57:43.206443+00:00

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "a9c7a10d6970"
down_revision: str | None = "f991fb728e0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
