"""add_yandex_id_to_user_model

Revision ID: f3dd333de96d
Revises: a29b065685e5
Create Date: 2025-04-03 20:37:09.889869+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3dd333de96d"
down_revision: Union[str, None] = "a29b065685e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("yandex_id", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "users", ["yandex_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "yandex_id")
    # ### end Alembic commands ###
