name: Linter

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff wemake-python-styleguide flake8-html

      - name: Run ruff (lint + format)
        run: |
          ruff check . --output-format=html > ruff-report.html || true
          ruff format --check .

      - name: Run WPS with HTML report
        run: |
          flake8 . --select=WPS --format=html --htmldir=flake8-report
          [ -d flake8-report ] || mkdir flake8-report
          echo "<meta http-equiv='refresh' content='0; url=index.html'>" > flake8-report/index.html

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: |
            ruff-report.html
            flake8-report/
